# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58dcb034abf7d5597f63d1d5edce8c4ba290e25d20668fbc661ad7165b5a4f5ee779ab4380e0a326069436976aa6b66045c6024a3a8a1f10ec4a58ad5c8f3c69

test:
  secret_key_base: 843fe2d1131fd211c8ca3b2974eb864060861ed58e2b0d214c81e593d78a75a163922da5ac4620ceb8c5437485f5695ffe71dfd803e64250e5dc9d7d5bd7778b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
